"use client";
import { useState } from "react";
export default function Dashboard(){
 const [query,setQuery]=useState(""); const [sent,setSent]=useState(false);
 return <main className="shell"><header className="topbar"><a className="brand" href="/" style={{textDecoration:"none",color:"inherit"}}><div className="brandMark">D</div><div><strong>Doctie</strong><span>AI Healthcare</span></div></a><nav><a href="/">Home</a><a href="/auth">Account</a></nav></header>
 <section className="hero"><div className="heroCopy"><div className="pill">PATIENT DASHBOARD</div><h1>How can we help<br/><span>today?</span></h1><p>Your healthcare tools, appointments and AI assistant in one place.</p></div>
 <div className="assistantCard"><div className="cardHeader"><div className="assistantAvatar">✦</div><div><strong>Doctie AI</strong><small>Ready to help</small></div></div><div className="chatArea"><div className="botBubble">Ask about symptoms, medicines, or your next healthcare step.</div></div><form className="chatInput" onSubmit={e=>{e.preventDefault();setSent(Boolean(query));setQuery("")}}><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Ask Doctie..."/><button>↑</button></form>{sent&&<small style={{display:"block",padding:"0 16px 14px",color:"#0c766d"}}>Your question is ready for Doctie AI.</small>}</div></section>
 <section className="section"><div className="sectionIntro"><span>QUICK ACTIONS</span><h2>Your care, simplified.</h2></div><div className="actionsGrid">{[["📅","Book Appointment","Find doctors and hospitals"],["🏥","Find Hospitals","Explore nearby care"],["💊","Medicine Info","Understand your medicines"],["❤️","Health Tools","Track everyday wellbeing"]].map(x=><a className="actionCard" href="#appointments" key={x[1]}><div className="actionIcon">{x[0]}</div><div><strong>{x[1]}</strong><p>{x[2]}</p></div><span>→</span></a>)}</div></section>
 <section className="section" id="appointments"><div className="sectionIntro"><span>UPCOMING CARE</span><h2>Your appointments</h2></div><div className="appointment"><div className="doctorAvatar">PS</div><div className="appointmentMain"><strong>Dr. Priya Sharma</strong><span>General Medicine</span></div><div className="appointmentTime"><strong>Tomorrow</strong><span>10:30 AM</span></div><b>Confirmed</b></div><button className="primary dashboardButton">+ Book new appointment</button></section>
 <section className="emergency"><div><span className="emergencyTag">EMERGENCY</span><h2>Need urgent help?</h2><p>For life-threatening emergencies, contact your local emergency service or go to the nearest emergency department. Doctie is not an emergency service.</p></div><button>Emergency help →</button></section></main>;
}